# Generated by Django 4.2.7 on 2025-12-12 17:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='اسم العائلة')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بتنسيق: '+999999999'. يسمح حتى 15 رقمًا.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users/profiles/', verbose_name='الصورة الشخصية')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_customer', models.BooleanField(default=True, verbose_name='عميل')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='آخر تسجيل دخول')),
                ('email_verified', models.BooleanField(default=False, verbose_name='البريد الإلكتروني موثق')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='رقم الهاتف موثق')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'المستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'عنوان الشحن'), ('billing', 'عنوان الفواتير'), ('both', 'كلاهما')], default='shipping', max_length=20, verbose_name='نوع العنوان')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(max_length=17, verbose_name='رقم الهاتف')),
                ('country', models.CharField(default='Saudi Arabia', max_length=100, verbose_name='الدولة')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='الحي')),
                ('street_address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('building_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المبنى')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('is_default', models.BooleanField(default=False, verbose_name='العنوان الافتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'العنوان',
                'verbose_name_plural': 'العناوين',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
