# Generated by Django 4.2.7 on 2025-12-12 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الخاصية')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'خاصية',
                'verbose_name_plural': 'الخصائص',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100, verbose_name='القيمة')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='لون (كود HEX)')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.attribute')),
            ],
            options={
                'verbose_name': 'قيمة الخاصية',
                'verbose_name_plural': 'قيم الخصائص',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الماركة')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='الشعار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'الماركة',
                'verbose_name_plural': 'الماركات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='رابط الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('ordering', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان Meta')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='وصف Meta')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='الفئة الأم')),
            ],
            options={
                'verbose_name': 'الفئة',
                'verbose_name_plural': 'الفئات',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='رابط المنتج')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='كود المنتج')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='الباركود')),
                ('description', models.TextField(verbose_name='الوصف الكامل')),
                ('short_description', models.TextField(max_length=500, verbose_name='الوصف المختصر')),
                ('product_type', models.CharField(choices=[('simple', 'منتج بسيط'), ('variable', 'منتج متغير'), ('digital', 'منتج رقمي')], default='simple', max_length=20, verbose_name='نوع المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر المقارنة')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر التكلفة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='معدل الضريبة %')),
                ('quantity', models.IntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='حد المخزون المنخفض')),
                ('manage_stock', models.BooleanField(default=True, verbose_name='إدارة المخزون')),
                ('stock_status', models.CharField(choices=[('in_stock', 'متوفر'), ('low_stock', 'مخزون منخفض'), ('out_of_stock', 'غير متوفر')], default='in_stock', max_length=20, verbose_name='حالة المخزون')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='الوزن (كجم)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='الطول (سم)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='العرض (سم)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='الارتفاع (سم)')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان Meta')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='وصف Meta')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='كلمات دلالية')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='عدد المبيعات')),
                ('wishlist_count', models.PositiveIntegerField(default=0, verbose_name='في قائمة الرغبات')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('out_of_stock', 'نفذت الكمية'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='الأكثر مبيعاً')),
                ('is_new', models.BooleanField(default=False, verbose_name='جديد')),
                ('ordering', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand', verbose_name='الماركة')),
                ('categories', models.ManyToManyField(related_name='products', to='store.category', verbose_name='الفئات')),
            ],
            options={
                'verbose_name': 'المنتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, max_length=100, verbose_name='النص البديل')),
                ('ordering', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'صورة المنتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['ordering', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='كود المتغير')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='سعر المقارنة')),
                ('quantity', models.IntegerField(default=0, verbose_name='الكمية')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='الوزن')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('attributes', models.ManyToManyField(to='store.attributevalue', verbose_name='الخصائص')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productimage', verbose_name='الصورة الخاصة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'verbose_name': 'متغير المنتج',
                'verbose_name_plural': 'متغيرات المنتج',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku', 'barcode'], name='store_produ_sku_3ef278_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_active'], name='store_produ_status_18453b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='store_produ_price_2d55a6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-sales_count'], name='store_produ_sales_c_dd1f02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
    ]
