# Generated by Django 4.2.7 on 2025-12-12 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('type', models.CharField(choices=[('cod', 'الدفع عند الاستلام'), ('credit_card', 'بطاقة ائتمان'), ('bank_transfer', 'تحويل بنكي'), ('wallet', 'محفظة إلكترونية')], max_length=20, verbose_name='النوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('instructions', models.TextField(blank=True, verbose_name='التعليمات')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('ordering', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('requires_online_payment', models.BooleanField(default=False, verbose_name='يتطلب دفع إلكتروني')),
                ('extra_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم إضافية')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للطلب')),
                ('max_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأقصى للطلب')),
            ],
            options={
                'verbose_name': 'طريقة الدفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('authorized', 'مصرح به'), ('captured', 'تم التحصيل'), ('partially_refunded', 'مسترد جزئياً'), ('refunded', 'مسترد'), ('failed', 'فشل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='رقم المعاملة')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='رد بوابة الدفع')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التصريح')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحصيل')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='إيصال الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='الطلب')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payment.paymentmethod', verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
